/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package budzet.view;

import budzet.controller.Obrada;
import budzet.controller.ObradaPrihod;
import budzet.controller.ObradaRashod;
import budzet.model.Prihod;
import budzet.model.Rashod;
import budzet.model.Stavka;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class IzbornikProzor extends javax.swing.JFrame {

    private DefaultTableModel m;
    private Obrada obrada;
    private DecimalFormat nf;
    private ObradaPrihod obradaprihod;
    private ObradaRashod obradarashod;

    private List<Stavka> stavka;

    /**
     * Creates new form IzbornikProzor
     */
    public IzbornikProzor() {
        initComponents();
        postavke();
    }

    private void postavke() {

        obradaprihod = new ObradaPrihod();
        obradarashod = new ObradaRashod();

        setTitle("Izbornik");

        DatePickerSettings dps = new DatePickerSettings(new Locale("hr", "HR"));
        dps.setFormatForDatesCommonEra("dd.MM.yyyy");
        dps.setTranslationClear("Očisti");
        dps.setTranslationToday("Danas");
        dpPocetak.setSettings(dps);
        DatePickerSettings dpss = new DatePickerSettings(new Locale("hr", "HR"));
        dpss.setFormatForDatesCommonEra("dd.MM.yyyy");
        dpss.setTranslationClear("Očisti");
        dpss.setTranslationToday("Danas");
        dpKraj.setSettings(dpss);

        DecimalFormatSymbols symbols = new DecimalFormatSymbols(new Locale("hr", "HR"));
        nf = new DecimalFormat("###,###.00", symbols);

        ucitaj();

    }

    private void ucitaj() {

        List<Stavka> stavka = new ArrayList<>();
        List<Prihod> prihod = obradaprihod.read();
        List<Rashod> rashod = obradarashod.read();

        if (txtTrazi.getText().isEmpty()||txtTrazi.getText().equals("Upiši naziv")||txtTrazi.getText().isBlank()) {
            stavka.addAll(prihod);
            stavka.addAll(rashod);
        }
        for (Prihod p : prihod) {

            if (txtTrazi.getText().equals(p.getVrsta().getNaziv())||p.getVrsta().getNaziv().contains(txtTrazi.getText())) {
                stavka.add(p);
            }
        }
        for (Rashod r : rashod) {

            if (txtTrazi.getText().equals(r.getVrsta().getNaziv())||r.getVrsta().getNaziv().contains(txtTrazi.getText())) {
                stavka.add(r);
            }
        }
        
        var z=BigDecimal.ZERO;
        for(Stavka s: stavka){
            z=s.getIznos().add(z);
        }
        
        txtUkupno.setText(z.toString());

        TablicaModelIzbornik m = new TablicaModelIzbornik(stavka);

        tbPregled.setModel(m);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPregled = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTrazi = new javax.swing.JTextField();
        dpPocetak = new com.github.lgooddatepicker.components.DatePicker();
        dpKraj = new com.github.lgooddatepicker.components.DatePicker();
        btnOsvjezi = new javax.swing.JButton();
        txtUkupno = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mPrihod = new javax.swing.JMenu();
        mRashod = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbPregled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPregled);

        jLabel1.setText("Traži");

        txtTrazi.setText("Upiši naziv");
        txtTrazi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTraziFocusGained(evt);
            }
        });
        txtTrazi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTraziKeyTyped(evt);
            }
        });

        btnOsvjezi.setText("Osvježi");
        btnOsvjezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsvjeziActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        mPrihod.setText("Prihod");
        mPrihod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mPrihodMouseClicked(evt);
            }
        });
        jMenuBar1.add(mPrihod);

        mRashod.setText("Rashod");
        mRashod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mRashodMouseClicked(evt);
            }
        });
        jMenuBar1.add(mRashod);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dpPocetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(dpKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOsvjezi)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dpPocetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(293, 293, 293)
                        .addComponent(btnOsvjezi)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mPrihodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mPrihodMouseClicked
        new PrihodProzor().setVisible(true);
    }//GEN-LAST:event_mPrihodMouseClicked

    private void mRashodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mRashodMouseClicked
        new RashodProzor().setVisible(true);
    }//GEN-LAST:event_mRashodMouseClicked

    private void txtTraziFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTraziFocusGained
        txtTrazi.setText("");
    }//GEN-LAST:event_txtTraziFocusGained

    private void btnOsvjeziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsvjeziActionPerformed
        ucitaj();
    }//GEN-LAST:event_btnOsvjeziActionPerformed

    private void txtTraziKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraziKeyTyped
        ucitaj();
    }//GEN-LAST:event_txtTraziKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOsvjezi;
    private com.github.lgooddatepicker.components.DatePicker dpKraj;
    public com.github.lgooddatepicker.components.DatePicker dpPocetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mPrihod;
    private javax.swing.JMenu mRashod;
    private javax.swing.JTable tbPregled;
    private javax.swing.JTextField txtTrazi;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables

}
